
ALTER TABLE STUDENT ADD FOREIGN KEY(advisor_id) REFERENCES STUDENT_ADVISOR(advisor_id);

ALTER TABLE STUDENT ADD FOREIGN KEY(PLACE_NUM) REFERENCES ROOM(PLACE_NUM);

ALTER TABLE RESIDENCE_HALL ADD FOREIGN KEY(PLACE_NUM) REFERENCES ROOM(PLACE_NUM);

ALTER TABLE STUDENT_FLAT ADD FOREIGN KEY(PLACE_NUM) REFERENCES ROOM(PLACE_NUM);

ALTER TABLE LEASES ADD FOREIGN KEY(std_id) REFERENCES STUDENT(std_id);

ALTER TABLE LEASES ADD FOREIGN KEY(PLACE_NUM) REFERENCES ROOM(PLACE_NUM);

ALTER TABLE INVOICES ADD FOREIGN KEY(std_id) REFERENCES STUDENT(std_id);

ALTER TABLE INVOICES ADD FOREIGN KEY(PLACE_NUM) REFERENCES ROOM(PLACE_NUM);

ALTER TABLE INVOICES ADD FOREIGN KEY(lease_num) REFERENCES LEASES(lease_num);

ALTER TABLE INVOICES ADD FOREIGN KEY(payment_id) REFERENCES PY_INVOICES(payment_id);

ALTER TABLE FLAT_INSPECTIONS ADD FOREIGN KEY(PLACE_NUM) REFERENCES ROOM(PLACE_NUM);

ALTER TABLE FLAT_INSPECTIONS ADD FOREIGN KEY(staff_num) REFERENCES HOSTEL_STAFF(staff_num);

ALTER TABLE FLAT_INSPECTIONS ADD FOREIGN KEY(FLAT_num) REFERENCES STUDENT_FLAT(FLAT_num);

ALTER TABLE HOSTEL_STAFF ADD FOREIGN KEY(PLACE_NUM) REFERENCES ROOM(PLACE_NUM);